language: ruby
rvm:
  - 1.9.3
install:
  # git clone --depth=50 --branch=master git://github.com/gitinsky/ansible-role-lxc.git gitinsky/ansible-role-lxc && cd gitinsky/ansible-role-lxc
  # sudo apt-get install -y software-properties-common python-software-properties wget curl git
  - sudo wget -c https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - curl https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
  - echo "deb http://download.virtualbox.org/virtualbox/debian/ precise contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y virtualbox-4.3 dkms python git software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
  # - sudo apt-get install linux-headers-$(uname -r)
  - sudo apt-get install -y linux-headers-generic linux-headers-virtual
  - sudo apt-get install -y linux-image-generic-lts-raring linux-headers-generic-lts-raring
  - mkdir -vp examples/roles
  - git clone https://github.com/gitinsky/ansible-role-common-utils.git examples/roles/common-utils
  - git clone https://github.com/gitinsky/ansible-role-certificates.git examples/roles/certificates
  - git clone https://github.com/gitinsky/ansible-role-nginx.git        examples/roles/nginx
  - ln -vs ../../ examples/roles/lxc
before_script:
  - cd examples/roles/common-utils && git pull && cd ../../../
  - cd examples/roles/certificates && git pull && cd ../../../
  - cd examples/roles/nginx        && git pull && cd ../../../
  - VBoxManage --version
  - sudo /etc/init.d/vboxdrv setup
  - VBoxManage --version
  - ls
  - pwd
  - uname -a
  - uname -r
  - sudo reboot
script:
  - sudo modprobe vboxdrv
  - vagrant up --no-provision lxc_12
  - vagrant halt -f lxc_12
  - VBoxManage modifyvm lxc_12 --uart1 0x3F8 4 --uartmode1 file "/tmp/lxc_12"
  - vagrant up --no-provision lxc_12
  - cat /tmp/lxc_12
  - vagrant provision lxc_12
  - cat /tmp/lxc_12
  - vagrant up --no-provision lxc_14
  - vagrant provision lxc_14
